language: r
r: bioc-devel
cache: packages
sudo: true

before_install:
  - tlmgr install bera nowidow parnotes marginfix etoolbox titlesec sectsty framed enumitem parskip soul placeins footmisc changepage xstring caption mathtools 

apt_packages:
  - libnetcdf-dev
  - texlive-full  

r_packages:
  - covr

bioc_packages:
  - AnnotationDbi
  - annotate
  - pRolocdata
  - MLInterfaces
  - synapter

r_github_packages:
  - MangoTheCat/visualTest

r_check_args:
  --no-vignettes
  --no-build-vignettes

r_build_args:
  --no-build-vignettes
  
after_success:
  - Rscript -e 'covr::codecov()'

# print timings (of examples) and sysinfo
after_script:
  - dump_logs_by_extension "timings"
  - dump_sysinfo

notifications:
  email:
    on_success: lg390@cam.ac.uk
    on_failure: lg390@cam.ac.uk

